### ISSUE TITLE
How to deal with the attributes

### ISSUE THREAD

**Issue by doomlab** [debruine/ddcreator#5]
#2 related to this issue. @ajhmohr 

```unique_vals <- sort(unique(rawdata[,theCol]))
unique_desc <- unique_vals
# TODO: get unique_desc from attributes if they exist
```

Currently we pulling from the raw data and then saving in attribute_storage. This resets to raw data if you change columns and come back (re-editing). Instead we should populate attribute_storage on the raw data load, and pull the levels tables from attribute storage to edit. 

So function that takes attribute storage and turns it in to the attributes for the original data to create .Rdata output (which can be used for json, etc.).

**Comment by debruine** [comment]
Sorted. It still saves and reads from the attribute_storage object, which may need to be converted to dataframe column attributes @ajhmohr
